print(´ola, mundo´)
print(´mundo incrivel´)
print(´dia ensolarado´)
print(`hoje o dia ta bonito`)
print(´sextou´)
print(´feliz natal´)
print(´final de samana´)
print(´ola , tudo bem?´)
print(´vai chover´)
print(´sol quente´)